### ISSUE TITLE
ANTIC-015 Case:Test not valid

### ISSUE THREAD

**Issue by hakson** [sw21-tug/Team_27#15]
As a user

I want to get informed if my test result is not valid

so that I can test myself again

if users adds testID which carries "not valid" result
pop up window will show with information:
" Unfortunately, your test result is not valid.
  QR code couldn't be generated.
  To make sure that you are negative on 
   Corona-virus, please test your self again. "

User should be able to confirm this message,
after confirmation user is redirected to the
add test report screen.

**Comment by AndreasKohl** [comment]
We don´t do this user story.
