### ISSUE TITLE
ANTIC-002 Notification of test

### ISSUE THREAD

**Issue by hakson** [sw21-tug/Team_27#2]
As a user 

I want to be notified if my test is positive

by email

so that I can adapt my behaviour 

The e-mail construction:

"Dear Mr/Mrs *Surname*

you have been testet positiv on Covid-19 virus.
Shortly you will be contacted by official institution
about your next preventive steps.

If you have some questions about general information, 
such as how it is passed on, symptoms and prevention,
you can call this number from AGES Austrian Agency for Health and Food Safety)
seven days a week.    0800 555 621

If you have genuine symptoms (a high temperature, a cough, shortness of breath), 
stay at home and please call the health hotline on +43 1 1450 to receive information on the next steps (diagnosis). 0:00 – 24:00.

Kind regards and stay healthy
your ANTI COVID Team. "

**Personal user information such as surname is parsed automatically in e-mail.

examples: 
PCR-00-12345(negative)
PCR-01-12345(positive)
pharmacy,(PHA-00-12345)
antigen tests(ANT-00-12345)

**Comment by AndreasKohl** [comment]
Wer do not implement  this feature, because we solved it in another story.
