### ISSUE TITLE
ANTIC-019 Hotlines

### ISSUE THREAD

**Issue by hakson** [sw21-tug/Team_27#28]
As an app user, 

I want to be able to see various hotlines for hotlines, which can answer questions (general, travel, work, etc.) in relation to coronavirus, and can also provide advice so that I can receive further information or answers to my questions.

The button for this screen should be added on the home screen
By clicking on it, this new Hotlines screen is opened with further informations.

"
Coronavirus hotline of the AGES (Austrian Agency for Health and Food Safety): 0800 555 621 (this line bold)

The AGES answers questions on the topic of coronavirus (general information about how it is passed on, symptoms and prevention)  seven days a week on 0800 555 621. (normal font)

Health advice hotline 1450 (bold)

If you have genuine symptoms (a high temperature, a cough, shortness of breath), stay at home and please call the health hotline on +43 1 1450 to receive information on the next steps (diagnosis). 0:00 – 24:00. (normal font)

Questions related to care and support – hotlines provided by the provinces (BOLD)

The following hotlines offer information in relation to 24-hour care and looking after family members when the carer(s) are unavailable or there are other problems due to the coronavirus measures.

Burgenland(bold)

Care advice: 05/7600-1000

Carinthia(bold)

Care hotline: 05/0536-22134

Lower Austria (Bold)

Care hotline: 02742/9005-9095

Upper Austria(Bold)

 Hotline (Caritas): 05/1775-775

Salzburg(Bold)

Salzburg care advice: 0662/8042-3533

Styria(Bold)

Care hotline: 0800/500 176

Tyrol

Coronavirus hotline: 0800/808030

Vorarlberg (Bold)

Care hotline: 05574/511-24105

Vienna(Bold)

Vienna Social Fund advice service: 01/24524 "

**Phone numbers can be called directly from the app.

**Comment by AndreasKohl** [comment]
We have this already in a tap
