### ISSUE TITLE
ANTIC-025 Research for User Statistics

### ISSUE THREAD

**Issue by toegl** [sw21-tug/Team_27#43]
Do some research about where we can get the data for the user statistics we plan to implement in the next sprints.

**Comment by AndreasKohl** [comment]
Result: @scampiiTU13 we discussed the results of the reseach.

- We want to add a news feed
- Default = austria
- It gives information about the situation about covid-19
- We will add other lands in Sprint 2
- It gives informations like today new covid-19 cases etc.

**Comment by scampiiTU13** [comment]
Github: https://github.com/chinghsuanwei/CovidLog
API: https://disease.sh/
Explanation: https://dev.to/bensalcie/android-kotlin-get-data-from-restful-api-having-multiple-json-objects-o5a
