### ISSUE TITLE
ANTIC-005 Notification case positive

### ISSUE THREAD

**Issue by hakson** [sw21-tug/Team_27#5]
As a user 
when i entered a positive test result.

I get information what i have to do next:

This text should be shown:
  """
  - When you have any questions call the 24h-Information-Hotline 0800 55 621!
  - Call ahead before visiting your doctor
  - Stay at home for 2 weeks
  - Separate yourself from other people
  - Clean your hands often
  - Avoid sharing personal household items
  - Clean all “high-touch” surfaces everyday

  If you get one or more signs of a heavy infection, which would be difficulty to breath, a fever, coughing badly or shortness of 
  breathing don't hesitate to call an ambulance (144)!
  """

And then
the user has to accept this with an Accept-button and will directed back to the "Home"-Screen.

In a dialog window.

![mockup_notification_case_positive_screen](https://user-images.githubusercontent.com/34246805/117980476-4ad3d500-b334-11eb-814b-8feced3c963b.png)

**Comment by toegl** [comment]
2 Screen should be implemented as shown in the mockups: positive test result
