### ISSUE TITLE
ANTIC-006 Notification case negative

### ISSUE THREAD

**Issue by hakson** [sw21-tug/Team_27#6]
As a user 

I want to add my testID(PCR, pharmacy, antigen)

in order to generate a QR code.

If a user adds test which carries negative result, 
pop up window will be shown with the message:

" You have been tested negative on Corona-Virus.
   Your QR code, based on the type of the test 
   will be generated and you can find it under QR codes screen
   stay healthy"

User should be able to confirm the message, 
after confirmation it is redirected to the home screen.

informations in QR code
Name, lastname
test type
test result

Consider adding additional information such as 
date of test,
 time of test,
time and date until the test is valid.

**Comment by toegl** [comment]
Screen should be implemented as shown in: [https://www.figma.com/file/aj001Tpv6ZVMzw07CeHLqO/COVID-19-Contact-Tracing-App-(Community)?node-id=39%3A75](mockups) (negative or not valid test result)
