### ISSUE TITLE
ANTIC-007 Vaccine ID

### ISSUE THREAD

**Issue by hakson** [sw21-tug/Team_27#7]
As a user 

I want to add my vaccine ID

to create my permanent QR code

informations in QR code
name, last name
vaccine manufacturer(Pfizer, AstraZeneca, Sputnik.....)
first dosis date
second dosis date

after login to the app
user should choose between options to add test results (testID)
or to add vaccine ID

**Comment by toegl** [comment]
2 Screens should be implemented as shown in the mockups: vaccine screen / not vaccinated and vaccine screen / vaccinated
